#!/system/bin/sh
#
# Copyright 2013, The SaberMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Scirpt by Paul Beeler (SparksCo)
# Check for double galleries and remove if needed
if [ -e /system/app/GalleryGoogle.apk ] && [ -e /system/app/GalleryGoogle-mako.apk ];
then
    # Multipule Galleries found, removing non-ROM one
    busybox sh /etc/mount-rw
    busybox rm /system/app/GalleryGoogle.apk
    busybox sh /etc/mount-ro
fi;

# Check for double video editors
if [ -e /system/app/VideoEditorGoogle.apk ] && [ -e /system/app/VideoEditorGoogle-mako.apk ];
then
    # Multipule video editors found, removing non-ROM one
    busybox sh /etc/mount-rw
    busybox rm /system/app/VideoEditorGoogle.apk
    busybox sh /etc/mount-ro
fi;
