# Version information used on all builds
PRODUCT_BUILD_PROP_OVERRIDES += \
    BUILD_VERSION_TAGS=release-keys \
    USER=android-build \
    BUILD_UTC_DATE=$(shell date +"%s")

# Set SM_BUILDTYPE

PRODUCT_VERSION_MAJOR := 1
PRODUCT_VERSION_MINOR := 1
PRODUCT_VERSION_MAINTENANCE := 0
SM_EXTRAVERSION := $(shell date +%s)

ifeq ($(SM_EXPERIMENTAL),1)
    SM_BUILDTYPE := EXPERIMENTAL
endif
ifeq ($(SM_RELEASE),I_AM_SABERMOD)
    SM_BUILDTYPE := RELEASE
    SM_BUILD := RC4
endif

ifdef SM_BUILDTYPE
    ifeq ($(SM_BUILDTYPE)-$(SM_RELEASE),RELEASE-I_AM_SABERMOD)
        SM_VERSION := $(TARGET_PRODUCT)-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)-$(SM_BUILD)
    else
        ifeq ($(SM_BUILDTYPE),EXPERIMENTAL)
            SM_VERSION := $(TARGET_PRODUCT)-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)-$(SM_EXTRAVERSION)-$(shell date -u +%m%d)
        endif
    endif
else
    # If SM_BUILDTYPE is not defined, set to UNOFFICIAL
    SM_BUILDTYPE := UNOFFICIAL
    SM_VERSION := $(TARGET_PRODUCT)-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)-$(SM_BUILDTYPE)-$(shell date -u +%m%d)
endif

PRODUCT_PROPERTY_OVERRIDES += \
  ro.sm.version=$(SM_VERSION) \
  ro.modversion=$(SM_VERSION)
