#!/system/bin/sh
#
# Copyright 2011-2013, The SaberMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Scirpt by Paul Beeler (SparksCo)
# Cycle bootanimations
if [ -d /system/media/bootanimations ];
then
    if [ -d /system/media/bootanimations/tmp ];
    then
        # Yay we already have a temp dir
        if [ -e /system/media/bootanimation.zip ];
        then
            busybox sh /etc/mount-rw;
            busybox mv /system/media/bootanimation.zip /system/media/bootanimations/tmp/1.zip;
            busybox mv /system/media/bootanimations/1.zip /system/media/bootanimation.zip;
            busybox mv /system/media/bootanimations/tmp/1.zip /system/media/bootanimations/1.zip;
            busybox sh /etc/mount-ro;
        else
            # Something went wrong here, bootanimation is missing!
            exit;
        fi;
    else
        busybox sh /etc/mount-rw;
        busybox mkdir /system/media/bootanimations/tmp;
        # Yay we now have a temp dir
        if [ -e /system/media/bootanimation.zip ];
        then
            busybox mv /system/media/bootanimation.zip /system/media/bootanimations/tmp/1.zip;
            busybox mv /system/media/bootanimations/1.zip /system/media/bootanimation.zip;
            busybox mv /system/media/bootanimations/tmp/1.zip /system/media/bootanimations/1.zip;
            busybox sh /etc/mount-ro;
        else
            # Something went wrong here, bootanimation is missing!
            busybox sh /etc/mount-ro;
            exit;
        fi;
    fi;
else
    # Something went wrong here, all the boot animations are missing!
    exit;
fi;

